{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\npytest_demo2.py:5: AssertionError"}, "start": 1567567694594, "stop": 1567567694594, "uuid": "df91bc67-99f4-42a0-916e-7f4936482d28", "historyId": "8fb1290a2c706e54d506222a6c10c0f7", "testCaseId": "aa3d737a1a96a367836cc3dd80016ba3", "fullName": "pytest_demo2#test_answer", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "pytest_demo2"}, {"name": "subSuite"}, {"name": "host", "value": "A010552-NC"}, {"name": "thread", "value": "17388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_demo2"}]}